[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "learning-siam-mae"
version = "0.1.0"
description = "A from-scratch re-implementation of SiamMAE (Siamese Masked Autoencoders for video), built as a learning project."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "Tomás Couso Coddou", email = "tomascousocoddou@gmail.com"}
]

dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "torch>=2.0.0",
    "torchvision",
    "pytorch-lightning",
    "pyyaml",
    "wandb",
    "pyrender",
    "trimesh",
    "pyglet<2",
    "tqdm",
    "pillow",
    "timm",        
    "networkx",
    "pyvista",
    "webdataset"
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pytest",
    "jupyter"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
