# Data & I/O
train_urls: "/workspace1/tcouso/learning-siam-mae/data/wds_mixed_shapes_color_100k/train/platonic-{0001..0004}.tar"
val_urls: "/workspace1/tcouso/learning-siam-mae/data/wds_mixed_shapes_color_100k/train/platonic-0001.tar"
batch_size: 40
num_workers: 16

# Training
max_epochs: 400
recon_log_every_n_steps: 500

# Compute & Hardware Routing
accelerator: "gpu"
devices: 1
strategy: "auto"
